### ISSUE TITLE
move COPYING file into readme.md file

### ISSUE THREAD

**Issue by bgruening** [galaxyproteomics/tools-galaxyp#11]
Can we remove the COPYING into `~` or put them into every readme.md file to get rid of it?
Now that we have one single galaxyp repository this would make much sense, imho.

@jmchilton ok with you? Your are probably the copyright holder?

**Comment by trevor** [comment]
As I understand it the existing tools have been developed under public funding and are therefore in the public domain. The copyright holders are listed in each separate tool in its respective README.

The licenses are assigned on a per-tool basis, instead of under a formally established project-wide charter.

This allows for the GalaxyP project to incorporate other tool contributions that may have more restrictive terms. The hope is that this provides the most flexibility and allows for the greatest developer freedom.

Feel free to bring this up on the mailing list if you'd like to discuss it further so more group members may participate. https://groups.google.com/a/umn.edu/forum/#!categories/galaxyp

**Comment by bgruening** [comment]
Ok, this is fine. Just thought about getting rid of the COPYING file :)
